### ISSUE TITLE
[Unpermaban] <AmbrosiaFumari>

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [discordia-space/wiki#10]
Так вот сам бан 
![screenshot_3](https://user-images.githubusercontent.com/43430615/48708141-bf6da300-ec12-11e8-8127-300c8633cbeb.png) 
Переехал к бабке на старый комп на нем получил банец на неделю за мемный ник, захожу посмотреть бан весить бан за мультиакк просьба сказать за кого я обходил "сикей" и что я делал я правда не знаю как такое произошло но думаю это лишь недоразумение и какая то ошибка, спасибо.

**Comment by SpadesSlick** [comment]
Анбан составлен не по форме, отклонено.
