### ISSUE TITLE
**[Unpermaban] <AmbrosiaFumari>** 

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [discordia-space/wiki#11]
1.![screenshot_4](https://user-images.githubusercontent.com/43430615/48708849-c39ac000-ec14-11e8-9c5b-a9afcb7c0a38.png)
2.История - Захожу на сервер с ником Ded Arkadii получаю бан на неделю, проверяю  уже бан по мультиакку. 
3.Не знаю в чем проблема ведь я даже не обходил банцы на Cev Eris, да и смысла я в этом не вижу,

**Comment by Voldirs** [comment]
Так как я не могу нормально проверить сиды по бд, я поменяю ризон. Напоминаю, что у амброзии уже был пермач на этом сервере, он слетел из-за смены бд, решили не возвращать сразу же, но тут повод довольно неприятный, поэтому я пожалуй оставлю как есть

**Comment by Voldirs** [comment]
Закрыто
