### ISSUE TITLE
**[Unpermaban] <AmbrosiaFumari>**

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [discordia-space/wiki#12]
1.![48708849-c39ac000-ec14-11e8-9c5b-a9afcb7c0a38](https://user-images.githubusercontent.com/43430615/50946201-64855900-14a9-11e9-8516-d16eb99c9a1b.png)

2.Перму считаю не оправданной, выдали перму за мультиакк а на самом деле за ник деда Аркадия, классная конечно причина возвращения пермы не спорю, но проблема в том что после моей первой пермы был большой промежуток времени возвращать перму оправдываясь причиной, дед Аркадий как то глупо.  

3.Я не против бана за мемные ники и мне его выдали, дали неделю вот и хорошо сижу и не выебываюсь, но выдавать после этого бан на мультиакк которого не было *Меня подставил проник который зашел за свои ебанные мультиакки и начал от моего лица всех грабить, резать, убивать, я не знаю что он у вас там делал* 

Заходил вчера на сервер _*Подтверждаю то что я начал обходить пермач_* посмотреть что вы там делаете и знаете что? Я считаю использовать вообще первую перму как оправдание моего бана вообще двулично,  на сервере люди режут друг друга натурально по любой причине, вспоминать перму  где меня забанил сам Носатый повелитель когда я нагнул половину корабля за червя, как то глупо

**Comment by Voldirs** [comment]
По поводу ситуации на сервере, всё так и есть, поэтому сначала почистим сервер, потом разбан будет. Ну и больше так не делай естественно. Поменял на три месяца.

**Comment by AmbrosiaBlyatFumari** [comment]
Бан поменял? А ок, все не обхожу.
