### ISSUE TITLE
**[Unban] <Grom260302> <Пермажоб и бан на день>**

### ISSUE THREAD

**Issue by Grom260302** [discordia-space/wiki#15]
Здрасьте. А у меня случилась такая досадная ситуация. Меня несколько не справедливо зажобали, так ещё и на непомерно большой срок с вот такой вот причиной.
The reason is: Расстрелял человека резиной и добил мечом вместо того чтобы связать. Аргументирует тем что человек под прицелом не сдался и сказал "Похуй". Таких оперативников хватает.
На старпома, кэпа и всю ЧВК.

А теперь к описанию ситуации.
Значит, дело было так. Разговаривал я с мозгом, на которого в бриге упало стекло, как мед.спец наймитов кричит 
 [Security] Arthur Caduel says, "Срочно оперативника в отдел криминалистики"
Я тут-же подорвался, сбегал к инспекторской, вспомнил про разделочный стол в бриге, пришёл туда. 
Arthur Caduel says, "Он на меня напал"
Arthur Caduel says, "И заварил" 
Услышал я когда туда зашёл. Диспозиция была такова. Я на лестнице. Передо мной напавший. За ним дверь, за которой стоит криминалист. 
Я прицелился в него, и приказал открыть дверь, сказав что у него три секунды
Operative Kaft aims FS CAR 6.5x39 "Sol" at Grayson Milred!
Operative Kaft says, "У тебя три секунды открыть дверь"
Operative Kaft says, "После твой ебальник станет украшением стекла"
Grayson Milred stutters, "я единственый живой техномансер"
Operative Kaft says, "Да мне поборту"
Operative Kaft says, "ШНЕЛЯ"
Operative Kaft says, "Считаю до трёх"
Operative Kaft exclaims, "Айн!"
Operative Kaft exclaims, "Цвайн!"
Grayson Milred stammers, "Похуй"
Operative Kaft exclaims, "Драйн!"
Кстати, если бы не его благополучное *Похуй*, всё было бы не так. А так, что мы видим? Ну, с точки зрения персонажа, а я стараюсь поступать с оной. На медика наймитов, в наймитской же базе напал какой-то хмырь, который на слова и ствол говорит "Похуй".. Ну, с точки зрения персонажа помоему это выглдядит так. Либо он во всю голову долбанутый, и за него даже никто не заплатит. Либо у него куча боевой аугументики, либо у него ещё какие-то секреты, которые собственно лучше не давать ему использовать. После чего я соответственно сделал ему в голове вмятину рубберами и завершил угрозу мечом. 
Я был бы согласен (Но не с такими сроками) с жобом в случае если бы это была стандартная станция со спейсло и прочим. Но это частный корабль. Это база наёмников. Где на медика этих наёмников (Единственного) напал какой-то хмырь, который не ясно как туда пробрался.
Кстати, до этого уже был кадр с аугументикой. Которая его не спасла. С его мозгом оперативник и разговаривал. Вот фрагментик. 
Ryan Stiller says, "Купил, как и имплант свободы. Как видишь, они оба мне не помогли" 
Собственно, вроде бы всё.

**Comment by Walfanger** [comment]
Ну, давай разберем по частям тобою написанное, как говорится.

1. Преступник в данной ситуации никак не мог навредить потерпевшему, заваренному в шкафчике;
2. Преступник не держал в руках оружия и не представлял собой угрозы, которая требует немедленной ликвидации.
С твоих слов записано верно?

Решается проблема очень просто: достаешь Мартин и кладешь нападавшего в стан, для последующего допроса и выбора меры пресечения.
А что сделал ты? 
Повелся на абсолютно идиотскую провокацию, чем продемонстрировал свою полнейшую некомпетентность в должности оперативника. И что это за "за него даже никто не заплатит", какая "база наемников"? Ты охотник за головами или сотрудник отдела корпоративной безопасности? Определись уж.

И я, к слову, молчу про твое вчерашнее заявление в ООС, которое полностью тебя дискредитирует и показывает намеренность твоего фрага:
"OOC: Grom260302/Grom260302 : На будущее
OOC: Grom260302/Grom260302 : Не стреляй в голову
OOC: Grom260302/Grom260302 : Если не хочешь **УБИТЬ**
OOC: Grom260302/Grom260302 : Ни руббером
OOC: Grom260302/Grom260302 : Ни чем"

Делаем выводы: у тебя либо мало игрового опыта, либо ты просто хотел кого-то убить.

**Comment by Grom260302** [comment]
Кхм. Я говорил про шкаф? 
Закрыт человек был в комнате. Преступник представлял собой угрозу тем, что каким-то образом крайне быстро проник в операционную брига, при том что я ходил от коридора, плюс игнорирует угрозу оружия, что для меня означает что имеет меры противодействия, аля аугументику или что-то подобное. Об этом написанно выше. 
Повёлся на идиотскую провокацию? У меня нападение на медика, напровоцировались.
Некомпетентность? Я отразил угрозу нападения. 
Для справки. Железный молот => ЧВК => наёмники. Они наняты капитаном. В каком смысле *Ты охотник за головами или сотрудник отдела корпоративной безопасности*? Раскрой пожалуйста.

А я говорил, что убил его не специально? Я в посте написал, цитирую, *После чего я соответственно сделал ему в голове вмятину рубберами и завершил угрозу мечом.* поскольку именно так поступил бы боец ЧВК при нападении странным типом с не менее странными возможностями на территорию ЧВК, разве нет?

**Comment by Grom260302** [comment]
Я пришёл. Преступник ходит туда-сюда под прицелом (Хм, нужно было не отключать запрет на ходьбу, наверное.) Я действовал как нормальный сотрудник ЧВК, на базу которого напали. 
Давай снова повторим. Если ему плевать на ствол => или ебанутый, или с секретом. Да и менять ствол практически в упор к противнику порой кончается плохо. Я указал тебе на то, что АйронХаммер не СБ НТ на станции НТ а нанятое ЧВК на личном судне. Который вопрос, я, кстати, проигнорировал? Выделяй жирным шрифтом не изменяя фразу, и уж точно не вырывая оную из контекста. Перечти то место, откуда её выделил. 
Оно не соответствует поведению станционного отдела.. Да я же писал это. Пожалуйста, прочти полностью а не избирательно.

**Comment by Doktor710** [comment]
Начнём с того что оперативник **отдела корпоративной охраны** Айронхаммера не должен убивать того кто не оказывает сопротивления, ты не убийца, не охотник за головами, ты защитник. 
Насчёт убийства, ты убил того кто не представляет угрозы, ты его обезвредил, но добил, оправдать тем что он на территории Айронхаммера нельзя, потому что это опять упирается в то, что ты убил человека, который не оказывал сопротивления.

**Comment by Walfanger** [comment]
Ты человека, который перед тобой ходил туда-сюда, застрелил. Просто так, когда тебе не мешало абсолютно ничего его заграбать и заковать в наручники, зафлешить мог бы, на худой конец, раз беготня его раздражала. Но тебе _"похуй"_ на это. На что я уже второй раз тебе указываю.

Хочешь прямую цитату? Пожалуйста: **"И что это за "за него даже никто не заплатит"?"** — вот эту часть моего вопросительного предложения ты проигнорировал.

При чем тут НТ и станция? Какой станционный отдел? Ты откуда взял это? Твое поведение ни отделу корпбезопасности Айронхаммера, ни какому-то станционному, как ты выражаешься, отделу, не соответствует. 
По слогам, медленно, прочитай: **тво-ё по-ве-де-ни-е не со-от-вет-ству-ет по-ве-де-ни-ю сот-руд-ни-ка от-де-ла кор-по-ра-тив-но-й бе-зо-пас-нос-ти Ай-рон-хам-ме-ра.** Ты понимаешь, о чем я тебе говорю тут? Ты понимаешь, что Айронхаммер имеет внутри себя пять отделов, и ты являешься сотрудником одного из них?

**Comment by Grom260302** [comment]
Прямая цитата *Либо он во всю голову долбанутый, и за него даже никто не заплатит. Либо у него куча боевой аугументики, либо у него ещё какие-то секреты, которые собственно лучше не давать ему использовать.*
Мешало заграбать и заковать в наручники то, что для этого было необходимо убрать человека с прицела, *похуй* было ему на наставленное оружие, на что я так-же обращаю твоё внимание. 
Кстати, какие пять отделов?..

**Comment by AmbrosiaBlyatFumari** [comment]
>прямая цитата Либо он во всю голову долбанутый
Operative Kaft says, "Да мне поборту"
Operative Kaft says, "ШНЕЛЯ"
Operative Kaft says, "Считаю до трёх"
Operative Kaft exclaims, "Айн!"
Operative Kaft exclaims, "Цвайн!"
Operative Kaft exclaims, "Драйн!" 
Тебе бы еще накинуть за мемы.

**Comment by AmbrosiaBlyatFumari** [comment]
> Начнём с того что оперативник **отдела корпоративной охраны** Айронхаммера не должен убивать того кто не оказывает сопротивления, ты не убийца, не охотник за головами, ты защитник.

Айронхаммер не защитники, это дисциплинированные наемыши которые выполняют работу за бабосы, они вполне могу перестрелять корабль с детьми если им дадут деньги *наверное*

**Comment by SpadesSlick** [comment]
Айронхаммер и есть Синдикат.

**Comment by AmbrosiaBlyatFumari** [comment]
> Айронхаммер и есть Синдикат.

ну тогда террористов-коммунистов ваще поебать.

**Comment by Grom260302** [comment]
Если в тебя иглой стрельнули, пока ты не упал по идее всем херачить можно

**Comment by AmbrosiaBlyatFumari** [comment]
> Если в тебя иглой стрельнули, пока ты не упал по идее всем херачить можно

заебашишь мимо трапа бан

**Comment by Grom260302** [comment]
Перма заслужена? Нихера себе, порядочки. Стреляющие иглы вроде тоже ярко пишет КТО стрельнул. 
Виноват в том, что ёбнул напавшего на базу, кря. 
Материя тут странная. Я её настроил, она дала немного энергии и взорвалась.

**Comment by seekin4u** [comment]
Материя не странная, просто не у всех людей достаточно интеллекта что бы делать по гайду и ничего не взрывать(не говорю уже о такой банальной вещи как чтение стандартной книги, в которой есть строчки об экстренном охлаждении)

**Comment by Grom260302** [comment]
Тема не к материи относится... Но когда я спрашивал у педали гайд, мне сказали что гайда нет и я делал как получилась..

**Comment by Grom260302** [comment]
Я действовал как поступил бы наёмник, который наставил на человека ствол, а ему поборту.. Господи, да я раза два точно это за время темы писал. Если бы я убрал ствол, а он из жопы хрень какую достал бы? 
Р-раз, и нет наёмника.

**Comment by Doktor710** [comment]
> Кстати, какие пять отделов?..

Expeditionary fleet. Созданный на деньги оставшихся планетарных государств и крупных корпораций, это главная военная сила Ганзы, защищающая союз от внешнего вторжения.

Marshals. Они выполняют заказы организаций и государств на ловлю и уничтожение преступников за пределами зон влияния заказчика. По сути, охотники за головами. Не смотря на все усилия центрального командования, работа этого отдела часто становится причиной их конфликтов с местными подразделениями корпорации по достаточно очевидным причинам.

Special Anomalistic Unit (S.A.U.). Этот отдел был создан для обнаружения, сдерживания, уничтожения и охраны аномальных объектов. Именно они защищают Ганзу от коммунистического культа Эксельсиора, агентов НеоТеологии, генокрадов и прочих угроз, лежащих за гранью понимания обычного человека. Корабль “CEV Eris” может иметь на борту несколько оперативников этого отдела, нанятых для защиты экспедиции от угроз на исследуемых дереликтах. 

Corporate security. Отдел отвечающих за охрану собственности, зданий, космических станций и судов. Охранный персонал “CEV Eris” является частью этого отдела.

Turing Police. Отдел по уничтожению не имеющих законов синтетиков, или же слишком мощных ИИ без надлежащей лицензии. Один из немногих отделов, действующих согласно своему уставу и не заключающих никаких контрактов, это очень влиятельная организация, получающая финансирование напрямую от союза.

> Айронхаммер не защитники, это дисциплинированные наемыши которые выполняют работу за бабосы, они вполне могу перестрелять корабль с детьми если им дадут деньги наверное

Возможно, но тут заплатили за защиту экипажа и корабля, что данные оперативники и должны делать, но не делают, а начинают вырезать экипаж при любой возможности.

**Comment by AmbrosiaBlyatFumari** [comment]
> Возможно, но тут заплатили за защиту экипажа и корабля, что данные оперативники и должны делать, но не делают, а начинают вырезать экипаж при любой возможности.
> Пока что я не вижу ни единой причины снимать бан, вместо того чтобы спорить с администрацией о том как должно быть скажи почему мы должны тебя разбанить.

Я и не говорю что он сделал все правильно, тут платят именно за защиту корабля и экипаж ну и слушать Летеху.

>Я действовал как поступил бы наёмник, который наставил на человека ствол, а ему поборту.. Господи, да я раза два точно это за время темы писал. Если бы я убрал ствол, а он из жопы хрень какую достал бы?
Р-раз, и нет наёмника.

Братан если ты этим все будешь оправдывать иди вот лучше реально поиграй за техномансера или мобиус, больше пользы будет, нормальный бы человек вплотную к дебичу подошел и током ударил или же шокером а не резину в него пустил и добил еще напоследок, у тебя было дохуя вариантов а ты выбрал самый кровавый, ты виноват и никто другой.

**Comment by Grom260302** [comment]
О, Доктор, спасибо за отделы. Кстати, где ты их взял? Я этого в лоре не видел.

Почему меня стоит разбанить? Потому-что я стараюсь всегда поступать так, как поступил бы персонаж на такой должности, с таким прошлым. РД-экспедиционер-противник религии. Роботех-фанатик мехов, наёмник ЧВК, собственно. Так-же имеет место быть крайний перегиб со сроками. Я бы понял, если бы педаль со мной поговорил, немного поспорили, а не так что >твои аргументы инвалид, договорились мол, Гром, не надо так делать, по башне дадут-же, а не сразу пермажобочкой. К примеру, когда из за того, что я был РД-противником религии, мне опер и детектив на экспедиции шлёпнули весь научный отсек+ассистента, кроме одного который каким-то макаром через z-уровни свалил, никто никого не забанил. Да никто, вроде (Ну я точно.) и не жаловался, т.к. ситуация логично вышла из предыстории. Собственно как и здесь. Да, я признаю что поступил всё-же жестоко. Но! Если бы не это волшебное *Похуй*, сказанное им на направленный ствол, я бы действовал мягче. И я считаю, что за такой градус боязни за персонажа его всё-же впереди меня должны были забанить. 

Амброзия, за Мёбиус я достаточно поиграл, а местная материя, с её волшебными трубами действует мне на мозги.

**Comment by Voldirs** [comment]
Те персонажи, которые ты описал это тупо самые-самые банальные и плоские типажи, которые можно только придумать. Так что явно не повод для разбана, а скорее в повод не снимать бан.

По поводу того что мы не спорили, это неправда, я попросил нормальную аргументацию своим действиям и получил то же самое что ты привёл в своём анбане.

По поводу сроков, я думаю, меня многие в этом поддержат. Ты знал что делал и я не хочу чтобы такие как ты возвращались к такому чудейсному геймплею до того момента как ты поймёшь что ты делаешь не так.

А так как я вижу, что такое говно вполне может случиться не только на молотках, докидываю бан на три месяца. Может за это время что-то переосмыслишь. Все кто хотел высказаться, уже высказались, решено, закрыто

**Comment by Grom260302** [comment]
Легендарные педали... И тут такие имеются.. Жаль!
