### ISSUE TITLE
[Unban] <Ambrosiafumari>, <3 месяца>

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [discordia-space/wiki#16]
**Простите**                                         

Приветствую, это я снова, возможно я охуел, да, ведь меня разбанили с пермы а я еще выпрашиваю анбан с 3 месяцев при этом отсидев только неделю, ну я подумал просто что многовато это изначально бан был на неделю и даа, вообщем хотелось бы бан немножечко снизить хотя бы ну на недели две, многовато просто за ник Деда Аркадия....  
Ну или снять, как всегда до проеба, только договоримся что если я отыграю месяц то не будут вспоминать мой бан за Деда Аркадия.
А то мне не приятно что прошло буквально два года а мой бан за робастного глиста вспоминают как будто это было вчера.

**Comment by Voldirs** [comment]
Нет. Пока что не вижу никаких причин снижать срок.
