### ISSUE TITLE
[Unpermaban] <Pid0ras>

### ISSUE THREAD

**Issue by Azazel416** [discordia-space/wiki#17]
1.
![bandicam 2019-01-23 22-37-20-645](https://user-images.githubusercontent.com/46965768/51613993-b1fcce00-1f5f-11e9-9e8f-0fdb812e7633.jpg)
2. Зашел первый раз в игру, хотел обучиться игре и по незнанию снял с себя одежду. Так же, я, для проверки работы чата, написал несвязный текст, после чего мне написал администратор, и сразу же выдал пермабан.
3. Я осознаю свою ошибку, научился базовым правилам игры и прошу получить разбан. Касательно никнейма: в случае, если мой никнейм не соответствует правилам сервера, то я с радостью готов его поменять.

**Comment by Voldirs** [comment]
Поменяй уж, да

**Comment by Voldirs** [comment]
Разбанено
