### ISSUE TITLE
**[Unpermaban] <Mr.Slepoi>**

### ISSUE THREAD

**Issue by Slepoi** [discordia-space/wiki#18]
**[Unpermaban] <Mr.Slepoi>**

Здравствуйте, меня забанили на сервере ( CEV Eris RU byond://syndi-cat.com:2511 ). За использование запрещенных фраз таких как "Героям слава, слава Украине", "АУЕ Братва". Я был на эмоции и рад что меня откачали. И вернули к игре, так как я пролежал полумертвый около 20-30 минут в ожидании чуда и не выходил в режим наблюдателя.  И когда ляпнул такие не хорошие фразы, вспомнил что нельзя было, понятное дело слово не воробей вылетит не поймаешь, за что искренне каюсь. 

А так же прошу прощения за не доделанные ПРы. Я испугался того что я не смогу сделать правильно и довести код до конца. Но сделал таким поступком еще хуже ситуацию. Мне нужно было не бояться и спрашивать у людей как это все делать, ведь коллектив адекватный и спокойно относится к проблемам, а так же помогут. Мне предлагали помощь, но я боялся что сделаю это, будут еще больше ошибки и проблемы.

Фрагмент из игры:
Я был торговцем. У меня был шеф с которым мы весело проводили время,  продавали товары. В какой то момент я зашел к шефу в кабинет через разбитое окно которое я разбил тапками, чтобы достучаться до него, так как он сидел в кабинете и решил посидеть на его личном стуле, за что был наказан выстрелом из дробовика резиновыми патронами.  Мы заказали оружие, он достал дубинку и избил меня за то что я решил попалить из купленного оружия. Он вырубил меня оглушающей дубинкой и я вырубился, он меня раздел, забрал все вещи которые были и вышвырнул на улицу. А сам ушел по делам. Я решил отомстить ему, залез на стол и пролез в его кабинет, а там украл его стул. Сел на него и стал ждать, он удивился и стал вытаскивать меня на стуле( на колесах). Между нами завязалась борьба. в итоге зашел СБ и уронил пистолет. Я схватил и стал стрелять чтоб от меня отошел. Но в итоге ничайно попал в СБ, шефа и стул. За стул обидно. Далее зашли еще люди и завязалась массовая драка, но я уже лежал без сознания и плохо все видно было. Потом я увидел как какой-то мужик меня вытаскивает из драки и тащит к себе в комнату ритуальную . Раздел и сделал мне штуку которая воскрешает. Я зашел за новое тело, и хотел ему служить. Мы вроде как подружились даже. Но в комнату зашел СБ и начал меня ловить, ему священник сказал чтоб не трогал меня и я изменился. Но СБ не слушался и бегал за мной вокруг стола. В итоге священник стал его бить и я. Он упал и потерял сознание. Я стал его быстренько раздевать и его тоже хотели ритуал провести. Но от драки и я потерял сознание и было много травм. Во время ритуала ворвались около 3-5 человек СБ, они забрали священника и своего СБ. А меня оставили одного на полу, в крови. Я так лежал около 20-30 минут, думал уже все, можно выходить из игры. Но тут зашел ко мне в комнату угадайте кто? Мой Шеф. Он меня утащил в мед отдел и меня стали лечить, когда мне вылечили челюсть, я от радости стал кричать радостные и смешные для меня фразы. Но потом опомнился и мне прилетел к сожалению бан. Прошу простить меня.

**Comment by Voldirs** [comment]
Учитывая тот факт, что писал ты как-то немногосложно, порой неграмотно, я с тебя попрошу написать какой-нибудь художественный рассказик или художественное описание персонажа. Не нужно писать много, нужно написать так чтобы было интересно читать. Тема рассказа не фиксированная, это не обязательно должно касаться ссочки.

**Comment by AmbrosiaBlyatFumari** [comment]
> я с тебя попрошу написать какой-нибудь художественный рассказик

Не ну это уже издевательство на уровне Тау а.к.а если хочешь вернуться пиши ржекич рассказ.
Типа как я понял главная причина бана это говно в ИС, ну пацан мемнул забанил бы на недельку че перму сразу, типа если ему уже давали предупреждение и карали по этому правилу то ладно ничего против не имею и да сколько Слепой играет в сску в целом никогда его не видел, честно. 

Бля понимаю когда меня сходу пермят с разворота по причине Амброзия Фумари но чет тут слишком жестко как то по инфинитивски прям.

**Comment by Slepoi** [comment]
@AmbrosiaBlyatFumari Согласен, какую ржаку историю рассказать?

**Comment by AmbrosiaBlyatFumari** [comment]
> @AmbrosiaBlyatFumari Согласен, какую ржаку историю рассказать?

Он просить написать историю которую будет интересно читать как квента на тау 
типа

**Comment by AmbrosiaBlyatFumari** [comment]
Ну на самом деле, я бы не пермил с ходу всех игроков с таким то онлайном в 10 человек, я понимаю что под вечер может набраться по 20 но если дальше так все пройдет через 3 месяца, я зайду на пустой сервер

**Comment by Voldirs** [comment]
Попрошу придерживаться темы, я больше жду ответа от слепого, сможет ли он что-то подобное написать или нет. Скажу сразу, перму я сниму в любом случае, с заменой на временный бан, но его продолжительность будет зависеть от того как будет выполнена моя просьба. Если чтиво будет годное, бан сниму сразу.
@Slepoi

**Comment by AmbrosiaBlyatFumari** [comment]
Ну че пацаны ТаУ квента за расперму...

**Comment by Voldirs** [comment]
Я так понял, что оп ничего не напишет, меняю бан на месяц в связи с его попытками контрибьютить до этой неприятной ситуации.
