### ISSUE TITLE
[Unban] Project Z reborn, 10080 minutes.

### ISSUE THREAD

**Issue by Zombuzi** [discordia-space/wiki#19]
Был я простым опером, после устранения всех грибов которые были ВЕЗДЕ, на втором часу раунда решил в РнД взять батарею для РИГ-а, прихожу, и вижу что РнД нихрена не изучено кроме хим спреера, при том, что у нас оверсир с недавно прибывшим роботехом. Разлочил консоль, и добавив некоторые свои батареи изучил супер-батареи, даже не гипер. После чего ко мне сразу же стучится вахтерыч, говоря что мол если есть доступ то не значит что умеешь. Может быть это и правда, но когда у нас с начала смены оверсир который нихуя не смыслит в РнД, то это куда хуже. После чего он сразу же говорит "Ну ок тогда сделаешь заявочку на разбан раз говорить не хочешь" и тут у меня немного пригорело, ведь говорил я с ним нормально и без матов. Ну и дальше получаю банан на весь состав айронхаммера, а затем сразу на всех глав, вахтер он на то и вахтер что бы вахтерить, хули. 
Подводя итог: Все что я сделал, это изучил 2 батареи, и все, работы я не отнимал у криворукого оверсира. Но ведь нельзя нахуй, священное РнД только для мебидиусов.
![unknown 1](https://user-images.githubusercontent.com/44114332/51904721-91ae9280-23e9-11e9-9c9b-9b5ed9aed09e.png)

Но все же круче всего, что за исследование двух батарей мне приписали что я саботажник, после чего ко мне подходят СБ и в открытую пытаются застрелить.

**Comment by Zombuzi** [comment]
LOOC  Alexandra Merryman: пи пи пу пу
LOOC Alexandra Merryman: я тупая шлюха
LOOC Alexandra Merryman: Готова сосать
Вот, админ которого мы заслужили, после того как мне отстрелили голову из-за создания батареи, он заходит в мое тело и пишет это в ЛООК.

**Comment by Voldirs** [comment]
(R)Alexandra Merryman/(Rationabilem)(JMP): пи пи пу пу
 (R)Alexandra Merryman/(Rationabilem)(JMP): я тупая шлюха
 (R)Alexandra Merryman/(Rationabilem)(JMP): Готова сосать

Это не админ если что, лол

**Comment by UberDanke** [comment]
Брать без разрешения глав РИГ в спокойные Часы раунда, лазать по шкафчикам глав, начать пальбу из летала по оперу, метагеймить по дикому. Бан ты заслужил, ебать.

**Comment by Z-Lore** [comment]
Не, я конечно прогорел с ЛООС. Так вот, я был тем оверсиром и я ВСЕГДА делаю исследования и знаю как это делать правильно, но вот незадача: я еще оказывается и глава, у которого есть обязанности вне научного отдела и это не дает тебе право начинать "делать науку" в то время как я отвлекся на проблемы экипажа. Мало того, тебе было этого мало и ты решил начать войну со всем экипажем. Не думаю, что тебя стал бы кто-то вязать за то, что ты был в рнд, если бы ты мог говорить (ведь когда я спрашивал что ты делаешь с консолью я получал нулевой ответ). И да, нормальные офицеры просто просят себе чтобы я им что-то сделал и знаешь что, я им делаю почти всё и бесплатно, только нужно немного подождать.
