### ISSUE TITLE
Morgue related respawn timer decrease doesn't work

### ISSUE THREAD

**Issue by kcalbxof** [discordia-space/wiki#21]
В случае если тело мертвеца пихнули в морг, то должно убавляться 8 минут от времени респавна, однако этого не происходит.

If dead body is placed in the morgue, respawn timer should be decreased by 8 minutes, but it doesn't happen.

**Comment by Voldirs** [comment]
Issues are to be writen in english. I will edit it myself.

**Comment by NanakoAC** [comment]
It only happens sometimes, which is a tricky problem, ill see what i can do though
