### ISSUE TITLE
[Jobbanhim] fghd, Sunshine Wollard (Course) 

### ISSUE THREAD

**Issue by Uvash** [discordia-space/wiki#24]
Будучи тритаром со следующими заданиями:

> Sunshine Wollard (Course) as an Assistant (fled the station)
Objective 1: Assassinate Isaac Clef, the Assistant.  Success!
Objective 2: Escape on the shuttle or an escape pod alive and free.  Fail. 

Производит качественный отыгрыш ТМ за ассистента трапика, убивая без какой-либо адекватной цели шахтёра (связал и скинул к тараканам) и священника (просто пристрелил)
[Логи на шахтёра.](https://pastebin.com/kdmqEieu)
[На священника.](https://pastebin.com/WNdBfePp)
Дополнительно, стоит отметить что всё это происходило при онлайне в 3 человека.
P.s.
Считаю что долгий бан на ролей, будет эффективнее чем обычный короткий, по этому прошу его.

**Comment by Coureere** [comment]
Стасян, ты забыл сказать, что после того, как я тебя просто связал и сказал, мол, мужик, ты щас сдохнешь, ты кинул мне пару угроз и ливнул из тела, а я с тобой ведь поговорить хотел про твои буржуйские замашки (ингейм) и не стал бы тебя убивать без особой причины, но твой персонаж решил забить к хуям на угрозу своему здоровью. Классно замалчивать свои косяки, требуя джобку за убийство будучи ролью, правда? И только после этого ты улетел к тараканам. Священником был ты же, и ты, отреспавнившись, сказал, что, мол, "готовь жопу" или что-то такое. Не вижу ничего такого, что мешает трейтору убить рандомного хуилу в конце раунда.

**Comment by Coureere** [comment]
Ты, к слову, один из самых говноедных игроков на ру сервере. Постоянно берёшь шахтёра, но никогда не копаешь, а вместо этого надеваешь риг и идёшь лутаться. Не нужно быть дебилом, чтоб сложить два плюс два и понять, что ты просто ради рига и ружья берёшь работу с зарплатой, доступом на склад гильдии, а потом тупо идёшь играешь в геймплей ассистента. Про отыгрышь можно не говорить, в принципе.

**Comment by AmbrosiaBlyatFumari** [comment]
Sunshine Wollard asks, "Будешь ещё заработок у ассистентов отнимать?" 
Uvash Cheese stammers, "Ты договор читала?" 
Sunshine Wollard says, "Хуеговор"
Sunshine Wollard says, "Ты зарплату получаешь" 
Sunshine Wollard says, "За раскопки."
Uvash Cheese stammers, "Ичто"
Sunshine Wollard says, "А не за оббирание техов."
Sunshine Wollard says, "Да мне **похуй**." 
Uvash Cheese stammers, "Всё брошенное"
Sunshine Wollard asks, "Чёж ты не ассистент тогда?" 
Sunshine Wollard says, "Нормально так напиздил."
Sunshine Wollard says, "А я потом хожу и ищу диски."
Sunshine Wollard says, "А их буржуй спиздил себе."
Sunshine Wollard asks, "Ну что, будешь ещё пиздить у **честного** люда?" 
Sunshine Wollard says, "Чё, сказать нечего" 
Uvash Cheese asks, "Ты понимаешь, что ты напала на работника гильдии?" 
Sunshine Wollard says, "Хуильдии"
Sunshine Wollard says, "Твоё тело никто не найдёт."
Sunshine Wollard says, "А твою запись я сотру." 
 Sunshine Wollard asks, "Есть что сказать то?" 
Uvash Cheese says, "Да я просто офигиваю ещё"  
Sunshine Wollard says, "Мужик, ты щас сдохнешь."
Sunshine Wollard asks, "Ты понимаешь?" 

Sunshine Wollard says, "Мужик, ты щас сдохнешь." 
Sunshine Wollard says, "Мужик, ты щас сдохнешь."  
>я с тобой ведь поговорить хотел 

Смешная ситуация, два дебила встретились один не хочет копать говно в шахтах и лутает техи а другой хотел разъебать другого чисто пофлексить робастом за трапика а причина стала тем что тот лутает его техи ну хули трапик доминирует, кожевник огребает не чо сказать не могу. 
>Дополнительно, стоит отметить что всё это происходило при онлайне в 3 человека. 

Онлайн всегда низкий иногда под ночь может набраться, че ты не вышел если 3 человека всего было или хотел налутать пушки и сам всех заробастить?

**Comment by Coureere** [comment]
Ну, тут всё видно. Я пытаюсь с тобой говорить, задаю тебе вопросы. Ты первый раз видишь поехавшего ассистента? Ты просто забил и ливнул из тела же, даже не пытался. В очередной раз доказал, что ты ущербен.

UPD: Только что заметил, что это не он, а блядский запермленец фумари. Иди нахуй из этого треда, Амброзия, ты чё, сидишь и мониторишь эту хуйню? Нахуй ты сюда лезешь, каждый раз обсираясь и защищая обосравшихся?

**Comment by Uvash** [comment]
> Стасян, ты забыл сказать, что после того, как я тебя просто связал и сказал, мол, мужик, ты щас сдохнешь, ты кинул мне пару угроз и ливнул из тела, а я с тобой ведь поговорить хотел про твои буржуйские замашки (ингейм) и не стал бы тебя убивать без особой причины, но твой персонаж решил забить к хуям на угрозу своему здоровью.

Мой персонаж впал в катонию, от безысходности (смирительная рубашка и наручники, так много шансов сбежать), но оставался жить. Ты же скинул куклу в теха к тараканам, обрекая куклу на смерть.
>Постоянно берёшь шахтёра, но никогда не копаешь, а вместо этого надеваешь риг и идёшь лутаться.

Бери кокпитона, отгоняй Жирис к астероидам. А так же завози Торговца, который договорится кому сбывать ресы и какие. Тогда буду копать. А так у меня возникает простой (читай свободное время), так что я лутаю техи в риге.

>Я пытаюсь с тобой говорить, задаю тебе вопросы.

Ну а я на них отвечаю. 

>Священником был ты же, и ты, отреспавнившись, сказал, что, мол, "готовь жопу" или что-то такое. 

А вот тут ты не прав, священником был не я.

>Не вижу ничего такого, что мешает трейтору убить рандомного хуилу в конце раунда.
Ну а я не вижу ни чего такого, что бы написать заявку на твой джоббан.

**Comment by AmbrosiaBlyatFumari** [comment]
> UPD: Только что заметил, что это не он, а блядский запермленец фумари. Иди нахуй из этого треда, Амброзия, ты чё, сидишь и мониторишь эту хуйню? Нахуй ты сюда лезешь, каждый раз обсираясь и защищая обосравшихся?

Смешной, я никого не защищаю вы оба дебилы и ты и он, я досих пор в бане выйду 04.10 жди дорогой. 

>Мой персонаж впал в катонию, от безысходности (смирительная рубашка и наручники, так много шансов сбежать), но оставался жить. Ты же скинул куклу в теха к тараканам, обрекая куклу на смерть. 
 
Один смешно маняврирует пытаясь оправдать свою зажаренную жопу 

>Sunshine Wollard says, "Мужик, ты щас сдохнешь."
 
А другой за трейтора ищет кому бы ебало разбить а потом в тредиках пиздить про то что игрок хуесос и вообще не ролеплей, на себя бы посмотрел трапик мускулистый на опухе тоже самое делал бил людям еблет за трапа и все. 
Как же хорошо по утрам заходить за сисястую куклу разъебывать еблеты тупым спермобакам аххх~~~ как же это ролеплейно

**Comment by Coureere** [comment]
> > Стасян, ты забыл сказать, что после того, как я тебя просто связал и сказал, мол, мужик, ты щас сдохнешь, ты кинул мне пару угроз и ливнул из тела, а я с тобой ведь поговорить хотел про твои буржуйские замашки (ингейм) и не стал бы тебя убивать без особой причины, но твой персонаж решил забить к хуям на угрозу своему здоровью.
> 
> Мой персонаж впал в катонию, от безысходности (смирительная рубашка и наручники, так много шансов сбежать), но оставался жить. Ты же скинул куклу в теха к тараканам, обрекая куклу на смерть.
> 
> > Постоянно берёшь шахтёра, но никогда не копаешь, а вместо этого надеваешь риг и идёшь лутаться.
> 
> Бери кокпитона, отгоняй Жирис к астероидам. А так же завози Торговца, который договорится кому сбывать ресы и какие. Тогда буду копать. А так у меня возникает простой (читай свободное время), так что я лутаю техи в риге.
> 
> > Я пытаюсь с тобой говорить, задаю тебе вопросы.
> 
> Ну а я на них отвечаю.
> 
> > Священником был ты же, и ты, отреспавнившись, сказал, что, мол, "готовь жопу" или что-то такое.
> 
> А вот тут ты не прав, священником был не я.
> 
> > Не вижу ничего такого, что мешает трейтору убить рандомного хуилу в конце раунда.
> 
> Ну а я не вижу ни чего такого, что бы написать заявку на твой джоббан.

Да, охуенная отговорка от кататонии, просто. Вот что ты сделаешь, если тебя поймает маньяк и скажет, что щас ушатает тебя нахуй? Впадёшь в кататонию? Начнёшь угрожать ему? Пиздец, охуительные истории. 

У моего персонажа вполне была мотивация тебя припугнуть, хотя бы, ибо ты лутаешь единственный способ заработка для него - техи. На работу ассистоту никто не берёт, да и некому. Ну а тут ещё и такая возможность подвернулась. К чему претензия, собственно?

С какого хуя, к слову, это я должен брать капитана, отгонять корабль и страдать хуйнёй? А может ты будешь ассистента брать, если видишь, что это сделать некому, вместо того, чтоб лутаться со шмотом шахтёра? Или может инженера возьмёшь и двигло сделаешь, м? А может сам капитана возьмёшь и отгонишь? Я СИЛЬНО сомневаюсь, что тебе настолько копать нравится, ибо это - самое унылое, что есть в билде. Да, конечно ты берёшь шахтёра не ради склада и рига.

**Comment by Uvash** [comment]
>Один смешно маняврирует пытаясь оправдать свою зажаренную жопу

Просто я понимал, что он меня или убьёт или закинет в дальний угол техтонелей. Нафига жрать это говно?

**Comment by AmbrosiaBlyatFumari** [comment]
> У моего персонажа вполне была мотивация тебя припугнуть, хотя бы, ибо ты лутаешь единственный способ заработка для него - техи. На работу ассистоту никто не берёт, да и некому. Ну а тут ещё и такая возможность подвернулась. К чему претензия, собственно?

 Колонист долго из себя дебила будешь строить, ты трейтор какой нахуй заработок, ты бабки получаешь за отрубленные еблеты и украденные вещи а не облутанных техов, коммунист блять нашелся. 

Лут ассистентам, шахты шахтерам, отделы работягам.
![58f90bee7522ca89008b4f80-750-563](https://user-images.githubusercontent.com/43430615/52637687-06e98f80-2ee1-11e9-99fa-34cfef1e9c15.jpg)

Думаю даже про священника говорить не стоит, у колониста взыграла паранойя робастера и думал что какой нибудь ехидный щенок с спины его баллоном разъебет, убрал священника дабы предотвратить возможную ситуацию.
{стрельба по ржачному священнику сапожнику и заковывание в наручи}
(follow) Stanley Blaskowitz says, "Ах ты еретик"
(follow) Stanley Blaskowitz asks, "В анальное рабство меня забираешь бесс ?"
(follow) Stanley Blaskowitz says, "Да как ты смеешь ничтожество"
(follow) Sunshine Wollard says, "Расскажи что-нибудь интересное."
(follow) Sunshine Wollard says, "А, ну да, ты же сдохнешь щас."
{показав свое доминирование над кожевником пристрелил к хуям}
(follow) Sunshine Wollard says, "Не повезло."
(follow) Sunshine Wollard says, "**Лох.**"

Показал так сказать где находится кожевный клуб

**Comment by AmbrosiaBlyatFumari** [comment]
Думаю даже про священника говорить не стоит, у колониста взыграла паранойя робастера и думал что какой нибудь ехидный щенок с спины его баллоном разъебет, убрал священника дабы предотвратить возможную ситуацию. 
{стрельба по ржачному священнику сапожнику и заковывание в наручи} 
(follow) Stanley Blaskowitz says, "Ах ты еретик" 
(follow) Stanley Blaskowitz asks, "В анальное рабство меня забираешь бесс ?" 
(follow) Stanley Blaskowitz says, "Да как ты смеешь ничтожество" 
(follow) Sunshine Wollard says, "Расскажи что-нибудь интересное." 
(follow) Sunshine Wollard says, "А, ну да, ты же сдохнешь щас." 
{показав свое доминирование над кожевником пристрелил к хуем}
(follow) Sunshine Wollard says, "Не повезло." 
(follow) Sunshine Wollard says, "Лох." 

Показал так сказать где находится кожевный клуб

**Comment by Ceka23** [comment]
Жоска

**Comment by AmbrosiaBlyatFumari** [comment]
Ну что все замолчали ребят, я то думал будете дальше на друг друга орать, жмите короче друг другу руки, миритесь, не деритесь, любите друг друга и ерпшьте хули вас и так мало а вы еще и ссоритесь с друг другом. 

 Дружба это магия пацаны может если вы подружитесь вы нарожаете онлайна ерису.

**Comment by Voldirs** [comment]
Задания трейтора не является такими уж принципиальными. Можно их выполнять, а можно их не выполнять если у тебя есть какая-то другая идея.
Ливать из тела когда тебя гопнули и даже не пытаться как-то словами выкрутиться это херня полная.
Ситуацию со святошей я нихуя не понял, но у меня такое предчувствие что если бы колонист его не уебал, то он бы залил всё тухловатыми мемесами.

Не так часто захожу на сервер, но когда я был, то постоянно видел ОПа в шахтёрах, подозреваю что всё это время, где-то неделю или пару недель он тупо аутировал в тоннели. Не знаю как насчёт колониста, но что-то мне подсказывает что тоже самое, только со стороны ассистента. Хорош аутировать, мэйк ролеплей грэйт эгэйн. Банов никому не будет потому что аутировать не запрещено. Увы.
