### ISSUE TITLE
[Unban] <Course>, <Пермаджоббан>

### ISSUE THREAD

**Issue by Coureere** [discordia-space/wiki#25]
Niccap решил пробанить меня перманентным джоббаном на все профессии молотков, первого офицера и капитана. Далее, цитата: "За ломание стекл брига отстреливает голову ассистенту и считает это нормальным" - так звучит ризон бана.

История началась с того, что я сидел в бриге во всеоружии и ждал нового появления террориста, который до этого бахнул пару бомб в научке и химии (получил информацию от МБО). Она попросила выдать ей оружие - выдал. Она выходит из брига. Слышу ЗВУК КРОШАЩЕГОСЯ СТЕКЛАx20 БАССБУСТЕД. МБО говорит по рации, что какой-то ассистент/инженер ломает стёкла. Выхожу посмотреть - там стоит какой-то бес-асисстент, весь в крови, а вокруг сломаны ВСЕ стёкла, до которых он дотянулся. Я тазерю его, кую в наручники, завожу в лобби брига под его бредовую ахинею, и, приняв решение, сношу ему голову на месте. Свои действия нахожу частично обоснованными по следующим причинам:

- Мой персонаж ждал появления опасного террориста во всеоружии и был, очевидно, на взводе, в голове продумывая завещание.

- МБО сообщила моему персонажу ранее, что на судне, возможно, есть мутант, а в частности, что скорее всего, террорист им и является. Можно посмотреть в логах.

- Ассистент, как таковой, согласно официальному описанию профессии де-факто НЕ ЯВЛЯЕТСЯ членом экипажа и выступает в качестве расходного человеческого материала. Не вижу ничего превратного в том, чтоб сделать из него пример для остальных или просто пустить в расход как слишком проблемного НЕ члена экипажа, который за всю смену достиг своего предела полезности в скоростном демонтаже стёкл просто по приколу.

- После смерти я обыскал его тело и нашёл револьвер, заряженный (магазинами от смг, когда уже пофиксите?) пистолет, наручники-стяжки из проводов. Для меня, лично, вооруженный ассистент при террористической угрозе - достаточно валидная цель для применения летального вооружения. Да, я не мог знать, но всё же, это может говорить о том, что мой персонаж всё-таки не ошибся.

- Так же, я поместил его тело в морг, тем самым сократив его респавн, ведь я не убил его просто затем, чтоб поглумиться над игроком/поржать.

Себя считаю частично виновным согласно правилу "Намеренное убийство\изоляция\причинение тяжкого вреда без основания", так как слишком, видимо, погорячился/переиграл. Лично игрок, который был убит, мотивация которого мне не ясна, своим иррациональным поведением и ахинеей мог частично попасть под нарушение правила "Нарушение атмосферы". Администратор же, который вместо вынесения справедливого решения и вызова третьей стороны (я просил вызвать педаль рангом выше), сказал, мол, "Я считаю это тупым бредом", "пермаджоб всего молота", "Знаÿ твой ПГ ты и за глав тоже самое сделал бы". Ну а я считаю, что пермаджоббаны на весь бриг и двух глав за единичный случай частичного (на мой взгляд) нарушения одного правила, отказ вызова третьей стороны, причина "по причине павергеймер, считаю это бредом, пермаджоббан, пиши жалобу" - крайне аутистичное поведение АДминистрации, которое не следует логике "Свода советов администрации", в частности части про "выносить справедливые решения" и "спроси у других администраторов". Неужели так сложно пингануть кого-нибудь в дискорде? Лучше же побыстрее забанить и забыть, действительно. Следуя из всего вышесказанного, прошу сократить количество забаненных профессий, в частности, исключив оттуда капитана, медэксперта, первого офицера (медэксперт не является боевой профой) и сократить пермабан до бана со сроком либо снять наказание (на усмотрение рассматривающего заявку). Логи [прикрепляю](https://pastebin.com/w1m8CVqJ). Что-то с логами случилось, но они, в принципе, читабельны при большом желании. Других нет, к сожалению, мб кто из других педалей отроет.

Отдельно прошу всяких дурачков вроде амброзий не превращать эту темку в цирк. Не нужно писать в тему, если вы не присутствовали/не были свидетелем/жертвой/педалью и так далее.

**Comment by Ruforce** [comment]
не читал но педаль дебил
пермаджоббаны не нужны

**Comment by AmbrosiaBlyatFumari** [comment]
Даже читать не буду, колонист ебанутый трапик доминатор, если нету нюковцев или охуевших трейторов он начнет доминировать над персоналом. 
Простите боссы качалки не нужны. 
![med_1508439033_image](https://user-images.githubusercontent.com/43430615/52762903-9babd480-302a-11e9-9ed9-0d3982b89128.jpg)

Эй дружок пирожок, я думаю ты выбрал неправильную дверь клуб боевого трапского мастерства двумя этажами ниже.

**Comment by 8161912** [comment]
Коурс все свои действия считает праведными и верными, даже отстрел головы ассистенту за битье стёкл для него было очередным подвигом, он отвечал на ПМки как будто спас всю станцию от фул отряда сербов, хотя убил всего одного ассистента. Уже после убийства и бана молота начал придумывать все возможные оправдания своим действиям, в которые входит его личное новое правило "Ассистент, как таковой, согласно официальному описанию профессии де-факто НЕ ЯВЛЯЕТСЯ членом экипажа и выступает в качестве расходного человеческого материала." ну и другие не менее плохие. При этом играя сам за ассистента считает себя богом на корабле, будь он тем ассистентом сразу бы заверещал в ахелп. Почему же бан не только на молот, но и на кепа и ФО, все просто, при малом онлайне подобные профессии не редко выполняют работу молота и при подобной ситуации я бы не удивился увидеть полное ее повторение.

**Comment by Coureere** [comment]
> Коурс все свои действия считает праведными и верными

> Себя считаю частично виновным

> было очередным подвигом, он отвечал на ПМки как будто спас всю станцию от фул отряда сербов, хотя убил всего одного ассистента

Только что это выдумал? По делу можно?

> личное новое правило

![image](https://i.imgur.com/o4Jn3wY.png)
Да, он нашёл своё призвание в битие стёкол, просто охуенно. Какой-то, возможно, безумный зек или бывший безбилетник может творить беспредел - это заебись, да. Нет, убивать нельзя.

А если серьёзно - если ты хоть немного играл, то должен понимать, что ассистенты - на пол шишечки выше бомжа без нихуя и ценятся соответственно. На своей практике знаю.

> играя сам за ассистента считает себя богом на корабле, будь он тем ассистентом сразу бы заверещал в ахелп

Опять из воздуха взял, особенно про "заверещал". Никто тебе не мешает зайти и въебать мне за наглость. Если ты про тот случай с метаместью - так это ты обосрался, не предприняв мер.

> Почему же бан не только на молот, но и на кепа и ФО, все просто, при малом онлайне подобные профессии не редко выполняют работу молота и при подобной ситуации я бы не удивился увидеть полное ее повторение.

Блять, я извиняюсь, но как же это малобуквенно. Ты в третий раз взял что-то из нихуя, часть про "при малом онлайне профессии выполняют работу молотка". Ну а чё ассистента не забанил ещё? Он вообще за все профы выполнять может нехило. У тебя вообще какая-то охуительная логика, твоё обвинение в целом какое-то несостоятельное.

В целом, я ожидал конструктивной критики моих действий, а получил малобуквенную хуйню по типу "свои действия считает праведными и верными" (спасибо, что залез мне в голову, посмотрел, что я там думаю, и отписался сюда, плотно держишь в курсе), "отвечал на ПМки как будто спас всю станцию от фул отряда сербов", "его личное новое правило", "считает себя богом на корабле", "сразу бы заверещал в ахелп", "Почему же бан не только на молот, но и на кепа и ФО, все просто, при малом онлайне подобные профессии не редко выполняют работу молота и при подобной ситуации я бы не удивился увидеть полное ее повторение." - полная цитата потому, что тут прекрасно всё. Ты вывалил своё личное мнение обо мне, а не фактическую обстановку по ситуации и не разбор нарушения, etc.

Я лучше подожду третью сторону, которая разберёт эту ситуацию, спасибо.

**Comment by IlyaIII** [comment]
В целом, шо тут можно сказать:
Радикальность действий, конечно же, имеется, что Коурс и подтверждает.
Бан выдан несколько оправданный, но слишком уж на долгое время, что, как мне кажется, надо бы и укоротить. 
А посему эту самую джобку, думаю, мы и уменьшим до недели, а т.к. 2 дня уже прошло, до пяти дней. 
И раз уж сам Коурс сказал, что четко понимает за что бан был выдан, как и признаёт себя виновным, хоть и частично, в следующий раз подобная ситуация повлечет более весомое наказание.

**Comment by Coureere** [comment]
> В целом, шо тут можно сказать:
> Радикальность действий, конечно же, имеется, что Коурс и подтверждает.
> Бан выдан несколько оправданный, но слишком уж на долгое время, что, как мне кажется, надо бы и укоротить.
> А посему эту самую джобку, думаю, мы и уменьшим до недели, а т.к. 2 дня уже прошло, до пяти дней.
> И раз уж сам Коурс сказал, что четко понимает за что бан был выдан, как и признаёт себя виновным, хоть и частично, в следующий раз подобная ситуация повлечет более весомое наказание.

А действие Никкапа никак не хочешь прокомментировать? Почему он решил, что выдавать пермаджоббан на добрую половину профессий за единичное нарушение - это нормально? Почему он решил, что руководствоваться личным мнением об игроке при выдаче бана и брать свои фантазии из головы на тему того, что я думаю и как считаю - это нормально? Этого, в целом, мало, чтоб написать жалобу, но почему такое говно осталось без внимания?

**Comment by IlyaIII** [comment]
А чтоб прокомментировать действия Никкапа, нужно не предположениями и выводами кидаться, а с ним это и обсуждать, что удобней делать где угодно, кроме как на гитхабе.
