### ISSUE TITLE
[Unban] AmbrosiaFumari 

### ISSUE THREAD

**Issue by AmbrosiaBlyatFumari** [discordia-space/wiki#27]
Отсидел 1-2 месяца, слезно выпрашиваю анбан или хотя бы снижение 4 месячного бана, вину признаю плохо поступил, выбирать ники по типу Дед Аркадий больше не буду, буду верно служить станции за Молотков и карать нечистивых антагонистов и защищать слабых,  онлайн и так маленький а так хоть иногда поддержу одним телом.  

Это последняя заявка по этому поводу если откажут буду дальше сидеть свой срок

**Comment by SpadesSlick** [comment]
>Заявка на снятие обычного бана может быть написана только один раз, перманентного - раз в три месяца

![image](https://user-images.githubusercontent.com/9161564/52880444-0e27cc00-3173-11e9-981c-dfb9165f6ed0.png)

Нет.
