### ISSUE TITLE
[Discord unban] koghs#2477

### ISSUE THREAD

**Issue by koghs** [discordia-space/wiki#9]
19.08.2018 я спровоцировал участников другого дискорд-канала. 
Методы провокации были довольно агрессивны и потому могли вызвать серьезный конфликт и неприятные разбирательства.
Хочу сказать что в действительности я не желал причинить вред кому-либо и это была крайне неудачная шутка за которую мне стыдно.

**Comment by SpadesSlick** [comment]
Ну раз стыдно, то ладно. Разбанен.
